version: '3.8'

services:
  kong:
    image: kong:3.4
    container_name: kong
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    volumes:
      - ./kong/kong.yml:/kong/kong.yml
    depends_on:
      - auth-service
      - document-service
      # - notification-service
      - interoperator-service
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    ports:
      - "6000:5000"
    depends_on:
      - rabbitmq
      - interoperator-service
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_HOST=rabbitmq
    networks:
      - app-network

  document-service:
      build: ./document-service
      ports:
       - "9080:8080"
      depends_on:
        - rabbitmq
        - interoperator-service
      networks:
        - app-network

  interoperator-service:
    build:
      context: ./interoperator-service
      dockerfile: Dockerfile
    environment:
        - NODE_ENV=test
        - OPERATOR_NAME=7894566124
        - OPERATOR_ADDRESS=Calle 7 N° 25  - 153, Medellín, Antioquia
        - OPERATOR_CONTACT_EMAIL=svp@gmail.com
        - OPERATOR_PARTICIPANTS1=Viviana Hoyos Sierra
        - OPERATOR_PARTICIPANTS2=Sergio A. Cordoba Muriel
        - OPERATOR_PARTICIPANTS3=Pablo Micolta Lopez
        - OPERATOR_TRANSFER_ENDPOINT=http://localhost:8000/comunication/transfers/process-transfer
        - OPERATOR_TRANSFER_ENDPOINT_CONFIRM=http://localhost:8000/comunication/transfers/confirm-citizen-transfer
        - API_BASE_URL=https://govcarpeta-apis-4905ff3c005b.herokuapp.com/apis
        - AUTH_SERVICE_URL=http://auth-service:5000/
        - DOCUMENT_SERVICE_URL=http://document-service:8080/
        - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    command: ["npm", "start"]
    ports:
      - "5002:3000"   # Expose service on port 5002
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # HTTP management console
    networks:
      - app-network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 60s
      retries: 5
      start_period: 10s
      timeout: 20s


networks:
  app-network:
    driver: bridge

  # notification-service:
  #   build: ./notification-service
  #   ports:
  #     - "5567:5001"
