bucket_name: document-service-api-storage
rabbitMQURL: amqp://guest:guest@rabbitmq:5672/
queue_names:
  - register_documents_queue
gov_carpeta_conf:
  base_url: govcarpeta-apis-4905ff3c005b.herokuapp.com
  timeout: 5s
  retry:
    quantity: 3
    strategy: exponential
    interval: 1000ms
    min: 1000ms
    max: 3000ms
  circuit_breaker:
    failure_ratio: 0.3
    min_observation: 10
    window: 5000ms
    cooldown: 1000ms
