version: '3.9'

services:
  interoperator-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
      - API_BASE_URL=http://mock-api:3000
      - AUTH_SERVICE_URL=http://auth-service:4000
      - DOCUMENT_SERVICE_URL=http://document-service:5000
      - RABBITMQ_URL=amqp://rabbitmq:5672   # Update to the internal RabbitMQ service URL
    depends_on:
      - rabbitmq
    command: ["npm", "run"]
    ports:
      - "5002:3000"   # Expose service on port 5002

  rabbitmq:
    image: rabbitmq:3-management  # RabbitMQ with management UI
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # HTTP management console
    networks:
      - app-network

networks:
  app-network:
    driver: bridge